name: Integracion Continua (CI)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v3
      
    - name: Configurar Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Dar permisos y ejecutar Pruebas Unitarias
      run: |
        chmod +x Backend/mvnw
        ./Backend/mvnw clean test -f Backend/pom.xml
